class Setting:
    AGENT_GROUP_NUM = 12
    AGENT_NUM_IN_ONE_GROUP = 10
    BETA = float(0.3)
    #20パーセント刻み
    GYOMU_NUM = 120
    SYUYAKUDO = 3
    UPDATE_NUM = 250
    PERCENTAGE_OF_LEARNING = 20
    TIMES_OF_SIMULATING = 50
    GROUP_DIFFERENCE =40


